Fix error on parallel multiple image pullings with additionallayerstore
Multiple parallel pullings of an image with additionallayerstore can occur the
following error:

```
Error: copying system image from manifest list: trying to reuse blob sha256:93ef9da9c5f3db2ac7fd52cab0e63c7e6fc9a722aec43d1b936a130e979ab8e8 at destination: failed to put layer from digest and labels: that ID is already in use
```

This commit fixes this issue by ignoring `ErrDuplicateID`. When the same layer
ID already exists in the storage, we can just reuse it instead of returning the
error. This is the same behaviour as when c/image uses `PutLayer`.

Signed-off-by: Kohei Tokunaga <ktokunaga.mail@gmail.com>