signing: clarify build error when cgo is not available
The build fails if CGO_ENABLED=0:

signature/mechanism_gpgme.go:156:41: undefined: gpgme.PinEntryLoopback
signature/mechanism_gpgme.go:161:31: undefined: gpgme.Key
signature/mechanism_gpgme.go:161:31: too many errors

Make it clear that cgo is required by adding a comment & undefined variable:

./mechanism_other.go:10:21: undefined: ContainersImageSignatureRequiresCgo

Anyone who encounters this error will immediately understand the issue and can
read the comment on that line to understand that the alternative build tag is
not actively maintained and considered not secure.

Signed-off-by: Christian Stewart <christian@paral.in>