INCOMPATIBLE: Remove the implementation of the ostree transport
Currently, ostree does not compile:

> ostree/ostree_dest.go:115:28: cannot use d (variable of type *ostreeImageDestination) as private.ImageDestinationInternalOnly value in argument to impl.AddCompat: *ostreeImageDestination does not implement private.ImageDestinationInternalOnly (missing method NoteOriginalOCIConfig) (typecheck)
> 	d.Compat = impl.AddCompat(d)

This has been broken since b941c6bf415cec5158dbbb822c26650420ad11bc (Nov 18 2024, > 4 months).

Previously:
- 807381f448c164bb81649ea1ad770609157efd9d (broken almost 4 months),
- 2e33bf7d272d97fba72e25964bc478eed8b028dd (broken > 7 months)

Overall, it seems extremely likely that noone is using the
containers_image_ostree build tag (off by default since March 2019).

So, finally, give up, and delete the code. Most importantly, this allows us
to delete the > 3-year-old-frozen dependency, and risky CGo code.

Signed-off-by: Miloslav Trmač <mitr@redhat.com>